name: cv_website
description: "Mikita Nikanovich CV website"
publish_to: "none"

version: 1.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  go_router: ^17.0.1
  flutter_svg: ^2.2.3
  equatable: ^2.0.8
  get_it: ^9.2.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  logger: ^2.6.2

  firebase_core: ^4.3.0
  firebase_database: ^12.1.1
  firebase_analytics: ^12.1.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:
  json_serializable: ^6.11.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/svg/
    - assets/files/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Bold.ttf
        - asset: assets/fonts/Oswald/Oswald-ExtraLight.ttf
        - asset: assets/fonts/Oswald/Oswald-Light.ttf
        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald/Oswald-SemiBold.ttf

flutter_gen:
  output: lib/src/assets
